#!/usr/bin/env bash
# Configures Nginx with a 301 redirect for /redirect_me
apt-get update -y
apt-get install -y nginx
sed -i '/server_name _;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
