#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing Ceci n'est pas une page
apt-get update -y
apt-get install -y nginx
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default
sed -i '/error_page 404/a\\tlocation = /404.html { internal; }' /etc/nginx/sites-available/default
service nginx restart
